package app

import (
	"github.com/dll/wxx/server/internal/auth"
	"github.com/dll/wxx/server/internal/handler"
	"github.com/gin-gonic/gin"
)

// registerVOPCRoutes 注册 vOPC 项目协作、交付、里程碑与风险治理路由。
func registerVOPCRoutes(secured *gin.RouterGroup, d *deps) {
	vopc := secured.Group("/vopc")
	vopc.Use(handler.CollegeAccess(d.cfg.VOPCCollegeID))

	vopc.GET("/access", d.vopcH.AccessStatus)
	vopc.GET("/learning", d.vopcH.Learning)
	vopc.GET("/guides", d.vopcH.Guides)
	vopc.GET("/users/search", d.vopcH.SearchUsers)
	vopc.GET("/projects", d.vopcH.ListProjects)
	vopc.POST("/projects", auth.RequireCapability(auth.VOPCProjectCreate), d.vopcH.CreateProject)
	vopc.POST("/demo-projects", auth.RequireCapability(auth.VOPCProjectCreate), d.vopcH.CreateDemoProject)
	vopc.POST("/projects/:id/simulation/advance", auth.RequireCapability(auth.VOPCProjectManage), d.vopcH.AdvanceSimulation)
	vopc.GET("/projects/:id", d.vopcH.GetProject)
	vopc.PUT("/projects/:id", auth.RequireCapability(auth.VOPCProjectManage), d.vopcH.UpdateProject)
	vopc.GET("/projects/:id/tasks", d.vopcH.ListTasks)
	vopc.GET("/projects/:id/decisions", d.vopcH.ListDecisions)
	vopc.POST("/projects/:id/decisions", auth.RequireCapability(auth.VOPCProjectManage), d.vopcH.CreateDecision)
	vopc.PUT("/projects/:id/decisions/:decisionId", auth.RequireCapability(auth.VOPCProjectManage), d.vopcH.ActDecision)
	vopc.GET("/projects/:id/members", d.vopcH.ListMembers)
	vopc.POST("/projects/:id/members", auth.RequireCapability(auth.VOPCProjectManage), d.vopcH.InviteMember)
	vopc.GET("/invitations", auth.RequireCapability(auth.VOPCProjectJoin), d.vopcH.ListMyInvitations)
	vopc.POST("/invitations/:invitationId/respond", auth.RequireCapability(auth.VOPCProjectJoin), d.vopcH.RespondInvitation)
	vopc.GET("/projects/:id/artifacts", d.vopcH.ListArtifacts)
	vopc.POST("/projects/:id/artifacts", auth.RequireCapability(auth.VOPCProjectManage), d.vopcH.CreateArtifact)
	vopc.GET("/projects/:id/artifacts/:artifactId/versions", d.vopcH.ListArtifactVersions)
	vopc.POST("/projects/:id/artifacts/:artifactId/versions", auth.RequireCapability(auth.VOPCProjectManage), d.vopcH.CreateArtifactVersion)
	vopc.POST("/projects/:id/files", auth.RequireCapability(auth.VOPCProjectManage), d.vopcH.UploadFile)
	vopc.GET("/projects/:id/files/:key", d.vopcH.DownloadFile)
	vopc.GET("/projects/:id/milestone-submissions", d.vopcH.ListMilestoneSubmissions)
	vopc.POST("/projects/:id/milestone-submissions", auth.RequireCapability(auth.VOPCProjectManage), d.vopcH.SubmitMilestone)
	vopc.GET("/projects/:id/ai-roles", d.vopcH.ListAIRoles)
	vopc.GET("/projects/:id/timeline", d.vopcH.ListTimeline)
	vopc.POST("/projects/:id/milestone-submissions/:submissionId/review", auth.RequireCapability(auth.VOPCMilestoneReview), d.vopcH.ReviewMilestone)
	vopc.GET("/projects/:id/rubrics", d.vopcH.ListRubrics)
	vopc.GET("/projects/:id/milestone-submissions/:submissionId/review", d.vopcH.GetSubmissionReview)
	vopc.PUT("/projects/:id/milestone-submissions/:submissionId/conditions/:conditionId", auth.RequireCapability(auth.VOPCProjectManage), d.vopcH.MarkConditionSatisfied)
	vopc.POST("/projects/:id/milestone-submissions/:submissionId/finalize", auth.RequireCapability(auth.VOPCMilestoneReview), d.vopcH.FinalizeMilestone)
	vopc.GET("/projects/:id/milestone-waivers", d.vopcH.ListMilestoneWaivers)
	vopc.POST("/projects/:id/milestone-waivers", auth.RequireCapability(auth.VOPCProjectManage), d.vopcH.CreateMilestoneWaiver)
	vopc.POST("/projects/:id/milestone-waivers/:waiverId/review", auth.RequireAnyCapability(auth.VOPCMentorReview, auth.VOPCMilestoneReview, auth.VOPCRiskManage), d.vopcH.ReviewMilestoneWaiver)
	vopc.GET("/projects/:id/client-evidence", d.vopcH.ListClientEvidence)
	vopc.POST("/projects/:id/client-evidence", auth.RequireCapability(auth.VOPCProjectManage), d.vopcH.CreateClientEvidence)
	vopc.PUT("/projects/:id/client-evidence/:evidenceId", auth.RequireCapability(auth.VOPCProjectManage), d.vopcH.UpdateClientEvidence)
	vopc.POST("/projects/:id/ai-tasks", auth.RequireCapability(auth.VOPCProjectManage), d.vopcH.CreateAITask)
	vopc.GET("/projects/:id/ai-tasks", d.vopcH.ListAITasks)
	vopc.GET("/projects/:id/ai-tasks/:taskId", d.vopcH.GetAITask)
	vopc.POST("/projects/:id/ai-tasks/:taskId/review", auth.RequireCapability(auth.VOPCProjectManage), d.vopcH.ReviewAITask)
	vopc.POST("/projects/:id/ai-tasks/:taskId/retry", auth.RequireCapability(auth.VOPCProjectManage), d.vopcH.RetryAITask)
	vopc.POST("/projects/:id/tasks", auth.RequireCapability(auth.VOPCProjectManage), d.vopcH.CreateTask)
	vopc.PUT("/projects/:id/tasks/:taskId", d.vopcH.UpdateTask)
	vopc.POST("/projects/:id/submit", auth.RequireCapability(auth.VOPCProjectManage), d.vopcH.SubmitProject)
	vopc.POST("/projects/:id/close", auth.RequireCapability(auth.VOPCProjectManage), d.vopcH.CloseProject)
	vopc.GET("/projects/:id/close-records", d.vopcH.ListCloseRecords)
	vopc.POST("/projects/:id/delete", auth.RequireCapability(auth.VOPCProjectManage), d.vopcH.DeleteProject)
	vopc.GET("/projects/:id/risks", d.vopcH.ListRisks)
	vopc.POST("/projects/:id/risks", auth.RequireCapability(auth.VOPCProjectManage), d.vopcH.CreateRisk)
	vopc.POST("/projects/:id/risks/:riskId/approve", auth.RequireAnyCapability(auth.VOPCRiskManage, auth.VOPCMentorReview), d.vopcH.ApproveRisk)
	vopc.GET("/projects/:id/special-approvals", d.vopcH.ListSpecialApprovals)
	vopc.POST("/projects/:id/special-approvals", auth.RequireCapability(auth.VOPCRiskManage), d.vopcH.CreateSpecialApproval)
	vopc.POST("/projects/:id/freeze", auth.RequireCapability(auth.VOPCRiskManage), d.vopcH.FreezeProject)
	vopc.POST("/projects/:id/risk-appeals", auth.RequireCapability(auth.VOPCProjectManage), d.vopcH.CreateRiskAppeal)
	vopc.POST("/projects/:id/risk-appeals/:appealId/resolve", auth.RequireCapability(auth.VOPCRiskManage), d.vopcH.ResolveRiskAppeal)
	vopc.POST("/projects/:id/governance-roles", auth.RequireAnyCapability(auth.VOPCRiskManage, auth.VOPCAudit), d.vopcH.GrantGovernanceRole)
}
